SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS banknote;
CREATE SCHEMA banknote;
USE banknote;

CREATE TABLE country (
	country_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	country_name VARCHAR(45) NOT NULL,
	country_code VARCHAR(15) NOT NULL,
	info TEXT,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (country_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE banknote (
	banknote_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	banknote_name VARCHAR(45) NOT NULL,
	banknote_code VARCHAR(15) NOT NULL,
	banknote_sign VARCHAR(15),
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (banknote_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE banknote_value (
	banknote_value_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	value INT UNSIGNED NOT NULL,
	image_link VARCHAR(255),
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (banknote_value_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE banknote_country (
	banknote_id SMALLINT UNSIGNED NOT NULL,
	country_id SMALLINT UNSIGNED NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (banknote_id, country_id),
	CONSTRAINT fk_banknote_country_banknote FOREIGN KEY (banknote_id) REFERENCES banknote (banknote_id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_banknote_country_country FOREIGN KEY (country_id) REFERENCES country (country_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE rate_exchange (
	base_banknote_id SMALLINT UNSIGNED NOT NULL,
	rate_banknote_id SMALLINT UNSIGNED NOT NULL,
	rate DECIMAL(12, 6),
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (base_banknote_id, rate_banknote_id),
	CONSTRAINT fk_base_rate_base FOREIGN KEY (base_banknote_id) REFERENCES banknote (banknote_id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_base_rate_rate FOREIGN KEY (rate_banknote_id) REFERENCES banknote (banknote_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;