INSERT INTO banknote (banknote_code, banknote_name) VALUES('AED', 'United Arab Emirates Dirham');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('AFN', 'Afghan Afghani');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('ALL', 'Albanian Lek');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('AMD', 'Armenian Dram');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('ANG', 'Netherlands Antillean Guilder');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('AOA', 'Angolan Kwanza');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('ARS', 'Argentine Peso');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('AUD', 'Australian Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('AWG', 'Aruban Florin');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('AZN', 'Azerbaijani Manat');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BAM', 'Bosnia-Herzegovina Convertible Mark');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BBD', 'Barbadian Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BDT', 'Bangladeshi Taka');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BGN', 'Bulgarian Lev');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BHD', 'Bahraini Dinar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BIF', 'Burundian Franc');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BMD', 'Bermudan Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BND', 'Brunei Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BOB', 'Bolivian Boliviano');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BRL', 'Brazilian Real');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BSD', 'Bahamian Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BTC', 'Bitcoin');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BTN', 'Bhutanese Ngultrum');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BWP', 'Botswanan Pula');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BYR', 'Belarusian Ruble');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('BZD', 'Belize Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('CAD', 'Canadian Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('CDF', 'Congolese Franc');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('CHF', 'Swiss Franc');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('CLF', 'Chilean Unit of Account (UF)');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('CLP', 'Chilean Peso');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('CNY', 'Chinese Yuan');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('COP', 'Colombian Peso');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('CRC', 'Costa Rican ColÃ³n');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('CUC', 'Cuban Convertible Peso');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('CUP', 'Cuban Peso');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('CVE', 'Cape Verdean Escudo');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('CZK', 'Czech Republic Koruna');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('DJF', 'Djiboutian Franc');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('DKK', 'Danish Krone');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('DOP', 'Dominican Peso');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('DZD', 'Algerian Dinar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('EEK', 'Estonian Kroon');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('EGP', 'Egyptian Pound');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('ERN', 'Eritrean Nakfa');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('ETB', 'Ethiopian Birr');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('EUR', 'Euro');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('FJD', 'Fijian Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('FKP', 'Falkland Islands Pound');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('GBP', 'British Pound Sterling');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('GEL', 'Georgian Lari');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('GGP', 'Guernsey Pound');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('GHS', 'Ghanaian Cedi');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('GIP', 'Gibraltar Pound');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('GMD', 'Gambian Dalasi');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('GNF', 'Guinean Franc');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('GTQ', 'Guatemalan Quetzal');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('GYD', 'Guyanaese Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('HKD', 'Hong Kong Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('HNL', 'Honduran Lempira');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('HRK', 'Croatian Kuna');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('HTG', 'Haitian Gourde');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('HUF', 'Hungarian Forint');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('IDR', 'Indonesian Rupiah');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('ILS', 'Israeli New Sheqel');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('IMP', 'Manx pound');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('INR', 'Indian Rupee');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('IQD', 'Iraqi Dinar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('IRR', 'Iranian Rial');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('ISK', 'Icelandic KrÃ³na');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('JEP', 'Jersey Pound');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('JMD', 'Jamaican Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('JOD', 'Jordanian Dinar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('JPY', 'Japanese Yen');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('KES', 'Kenyan Shilling');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('KGS', 'Kyrgystani Som');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('KHR', 'Cambodian Riel');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('KMF', 'Comorian Franc');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('KPW', 'North Korean Won');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('KRW', 'South Korean Won');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('KWD', 'Kuwaiti Dinar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('KYD', 'Cayman Islands Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('KZT', 'Kazakhstani Tenge');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('LAK', 'Laotian Kip');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('LBP', 'Lebanese Pound');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('LKR', 'Sri Lankan Rupee');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('LRD', 'Liberian Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('LSL', 'Lesotho Loti');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('LTL', 'Lithuanian Litas');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('LVL', 'Latvian Lats');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('LYD', 'Libyan Dinar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MAD', 'Moroccan Dirham');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MDL', 'Moldovan Leu');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MGA', 'Malagasy Ariary');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MKD', 'Macedonian Denar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MMK', 'Myanma Kyat');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MNT', 'Mongolian Tugrik');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MOP', 'Macanese Pataca');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MRO', 'Mauritanian Ouguiya');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MUR', 'Mauritian Rupee');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MVR', 'Maldivian Rufiyaa');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MWK', 'Malawian Kwacha');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MXN', 'Mexican Peso');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MYR', 'Malaysian Ringgit');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('MZN', 'Mozambican Metical');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('NAD', 'Namibian Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('NGN', 'Nigerian Naira');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('NIO', 'Nicaraguan CÃ³rdoba');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('NOK', 'Norwegian Krone');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('NPR', 'Nepalese Rupee');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('NZD', 'New Zealand Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('OMR', 'Omani Rial');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('PAB', 'Panamanian Balboa');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('PEN', 'Peruvian Nuevo Sol');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('PGK', 'Papua New Guinean Kina');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('PHP', 'Philippine Peso');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('PKR', 'Pakistani Rupee');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('PLN', 'Polish Zloty');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('PYG', 'Paraguayan Guarani');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('QAR', 'Qatari Rial');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('RON', 'Romanian Leu');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('RSD', 'Serbian Dinar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('RUB', 'Russian Ruble');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('RWF', 'Rwandan Franc');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SAR', 'Saudi Riyal');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SBD', 'Solomon Islands Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SCR', 'Seychellois Rupee');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SDG', 'Sudanese Pound');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SEK', 'Swedish Krona');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SGD', 'Singapore Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SHP', 'Saint Helena Pound');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SLL', 'Sierra Leonean Leone');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SOS', 'Somali Shilling');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SRD', 'Surinamese Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('STD', 'SÃ£o TomÃ© and PrÃ­ncipe Dobra');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SVC', 'Salvadoran ColÃ³n');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SYP', 'Syrian Pound');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('SZL', 'Swazi Lilangeni');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('THB', 'Thai Baht');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('TJS', 'Tajikistani Somoni');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('TMT', 'Turkmenistani Manat');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('TND', 'Tunisian Dinar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('TOP', 'Tongan PaÊ»anga');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('TRY', 'Turkish Lira');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('TTD', 'Trinidad and Tobago Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('TWD', 'New Taiwan Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('TZS', 'Tanzanian Shilling');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('UAH', 'Ukrainian Hryvnia');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('UGX', 'Ugandan Shilling');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('USD', 'United States Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('UYU', 'Uruguayan Peso');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('UZS', 'Uzbekistan Som');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('VEF', 'Venezuelan BolÃ­var Fuerte');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('VND', 'Vietnamese Dong');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('VUV', 'Vanuatu Vatu');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('WST', 'Samoan Tala');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('XAF', 'CFA Franc BEAC');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('XAG', 'Silver (troy ounce)');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('XAU', 'Gold (troy ounce)');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('XCD', 'East Caribbean Dollar');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('XDR', 'Special Drawing Rights');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('XOF', 'CFA Franc BCEAO');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('XPF', 'CFP Franc');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('YER', 'Yemeni Rial');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('ZAR', 'South African Rand');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('ZMK', 'Zambian Kwacha (pre-2013)');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('ZMW', 'Zambian Kwacha');
INSERT INTO banknote (banknote_code, banknote_name) VALUES('ZWL', 'Zimbabwean Dollar');
